In [ ]:
pip install textblob

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: textblob in /usr/local/lib/python3.8/dist-packages (0.15.3)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.8/dist-packages (from textblob) (3.7)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (7.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (4.64.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (2022.6.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (1.2.0)

In [ ]:
from textblob import TextBlob
import pandas as pd

In [ ]:
df=pd.read_excel("/content/mispelled words.xlsx")
df

                                      Misspelled Words
0           thier house was farther away from my plase
1     I think we would not be allive if our ancesto...
2    Imagine yourself you are working in factory ju...
3    For example , they can play fotball whenever t...
4    And young people spend more time on ther lifes...
..                                                 ...
96                                            maddness
97                                              latext
98                                             momento
99                                          imediately
100                                             falssh

[101 rows x 1 columns]

In [ ]:
def auto_correction(Word,i):
  word=TextBlob(Word)
  cor_word=word.correct()
  df['Corrected_words'][i]=cor_word

In [ ]:
df['Corrected_words']=0*len(df)
for i in range(len(df)):
  auto_correction(df['Misspelled Words'][i],i)

<ipython-input-118-48620ccbae0b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Corrected_words'][i]=cor_word
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
df

,Misspelled Words,Corrected_words
0,thier house was farther away from my plase,"(t, h, e, i, r, , h, o, u, s, e, , w, a, s, ..."
1,I think we would not be allive if our ancesto...,"( , I, , t, h, i, n, k, , w, e, , w, o, u, ..."
2,Imagine yourself you are working in factory ju...,"(I, m, a, g, i, n, e, , y, o, u, r, s, e, l, ..."
3,"For example , they can play fotball whenever t...","(F, o, r, , e, x, a, m, p, l, e, , ,, , t, ..."
4,And young people spend more time on ther lifes...,"(A, n, d, , y, o, u, n, g, , p, e, o, p, l, ..."
...,...,...
96,maddness,"(m, a, d, n, e, s, s)"
97,latext,"(l, a, t, e, s, t)"
98,momento,"(m, o, m, e, n, t)"
99,imediately,"(i, m, m, e, d, i, a, t, e, l, y)"
100,falssh,"(f, a, l, s, e)"

In [ ]:
df.to_csv("Corrected_words.csv")